name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish using nuke
        run: ./build.cmd Publish
        env:
          GH_TOKEN: ${{ github.token }}
          DOCKER_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKER_PASSWORD: ${{ secrets.dockerhub_token }}
